import { beforeEach, describe, expect, it, vi } from "vitest";
import type { ReactNode } from "react";
import { act, renderHook, waitFor } from "@testing-library/react";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ErrorCodes } from "@pombo/shared-types";
import { AppError } from "@/core/errors/AppError";
import { queryKeys } from "@/core/query/queryKeys";
import type {
  ApiTokenMetadata,
  GeneratedApiToken,
} from "@/modules/account/domain/entities/ApiToken";

const getApiTokenMock = vi.fn<[], Promise<ApiTokenMetadata | null>>();
const generateApiTokenMock = vi.fn<[], Promise<GeneratedApiToken>>();
vi.mock("@/core/di/repositories", () => ({
  repositories: {
    account: {
      getApiToken: () => getApiTokenMock(),
      generateApiToken: () => generateApiTokenMock(),
    },
  },
}));

const handleErrorMock = vi.fn();
vi.mock("@/core/query/useErrorHandler", () => ({
  useErrorHandler: () => ({ handleError: handleErrorMock }),
}));

const { useApiToken, useGenerateApiToken } = await import("./useApiToken");

const METADATA: ApiTokenMetadata = {
  prefix: "pmb_abcd…wxyz",
  createdAt: "2026-09-01T12:00:00.000Z",
  lastUsedAt: null,
};

function createClient() {
  return new QueryClient({
    defaultOptions: {
      queries: { retry: false, gcTime: Infinity, staleTime: Infinity },
      mutations: { retry: false },
    },
  });
}

function wrapperFor(client: QueryClient) {
  return function Wrapper({ children }: { children: ReactNode }) {
    return (
      <QueryClientProvider client={client}>{children}</QueryClientProvider>
    );
  };
}

beforeEach(() => {
  getApiTokenMock.mockReset();
  generateApiTokenMock.mockReset();
  handleErrorMock.mockReset();
});

describe("useApiToken", () => {
  it("loads the token metadata from the account repository", async () => {
    getApiTokenMock.mockResolvedValue(METADATA);
    const client = createClient();

    const { result } = renderHook(() => useApiToken(), {
      wrapper: wrapperFor(client),
    });

    await waitFor(() => expect(result.current.isSuccess).toBe(true));
    expect(result.current.data).toEqual(METADATA);
    expect(getApiTokenMock).toHaveBeenCalledTimes(1);
  });

  it("caches the metadata under the account api-token key", async () => {
    getApiTokenMock.mockResolvedValue(METADATA);
    const client = createClient();

    const { result } = renderHook(() => useApiToken(), {
      wrapper: wrapperFor(client),
    });

    await waitFor(() => expect(result.current.isSuccess).toBe(true));
    expect(client.getQueryData(queryKeys.account.apiToken())).toEqual(METADATA);
  });

  it("exposes null when the account never generated a token", async () => {
    getApiTokenMock.mockResolvedValue(null);

    const { result } = renderHook(() => useApiToken(), {
      wrapper: wrapperFor(createClient()),
    });

    await waitFor(() => expect(result.current.isSuccess).toBe(true));
    expect(result.current.data).toBeNull();
  });
});

describe("useGenerateApiToken", () => {
  it("returns the clear token generated by the repository", async () => {
    generateApiTokenMock.mockResolvedValue({ token: "pmb_secret" });

    const { result } = renderHook(() => useGenerateApiToken(), {
      wrapper: wrapperFor(createClient()),
    });

    let generated: GeneratedApiToken | undefined;
    await act(async () => {
      generated = await result.current.mutateAsync();
    });

    expect(generateApiTokenMock).toHaveBeenCalledTimes(1);
    expect(generated).toEqual({ token: "pmb_secret" });
    expect(handleErrorMock).not.toHaveBeenCalled();
  });

  it("invalidates only the api-token query on success", async () => {
    generateApiTokenMock.mockResolvedValue({ token: "pmb_secret" });
    const client = createClient();
    client.setQueryData(queryKeys.account.apiToken(), METADATA);
    const siblingKey = [...queryKeys.account.all, "profile"];
    const otherModuleKey = ["devices", "list"];
    client.setQueryData(siblingKey, {});
    client.setQueryData(otherModuleKey, []);
    const invalidateSpy = vi.spyOn(client, "invalidateQueries");

    const { result } = renderHook(() => useGenerateApiToken(), {
      wrapper: wrapperFor(client),
    });
    await act(async () => {
      await result.current.mutateAsync();
    });

    expect(invalidateSpy).toHaveBeenCalledTimes(1);
    expect(invalidateSpy).toHaveBeenCalledWith({
      queryKey: queryKeys.account.apiToken(),
    });
    expect(
      client.getQueryState(queryKeys.account.apiToken())?.isInvalidated,
    ).toBe(true);
    expect(client.getQueryState(siblingKey)?.isInvalidated).toBe(false);
    expect(client.getQueryState(otherModuleKey)?.isInvalidated).toBe(false);
  });

  it("routes a failure to the error handler without invalidating", async () => {
    const failure = new AppError("falhou", ErrorCodes.INTERNAL_ERROR, 500);
    generateApiTokenMock.mockRejectedValue(failure);
    const client = createClient();
    const invalidateSpy = vi.spyOn(client, "invalidateQueries");

    const { result } = renderHook(() => useGenerateApiToken(), {
      wrapper: wrapperFor(client),
    });
    act(() => {
      result.current.mutate();
    });

    await waitFor(() => expect(result.current.isError).toBe(true));
    expect(handleErrorMock).toHaveBeenCalledTimes(1);
    expect(handleErrorMock).toHaveBeenCalledWith(failure);
    expect(invalidateSpy).not.toHaveBeenCalled();
  });
});
